@startuml
hide footbox
participant "LTC Client" as ltcc

box "LTC Server"
    participant "Layman\nProxy" as ltcsproxy
end box
participant "Layman\nREST API" as layman

box "Authorization Server"
	participant "Introspection\nEndpoint" as lris
end box


ltcc [#0000FF]-> ltcsproxy: Request to\nLayman REST API
activate ltcc
activate ltcsproxy
note over ltcsproxy
    Proxy adds HTTP header
    Authorization
    to every request
    to Layman REST API.
end note
ltcsproxy [#FF0000]--> layman: Request to\nLayman REST API
activate layman
group Validation of Access Token
    note right of layman
        Validation of access token
        happens on every request
        to Layman REST API.
    end note
    layman [#FF0000]--> lris: Validate Access Token\nRequest
    lris [#FF0000]--> layman: Validate Access Token\nResponse
end
note over layman
    Now Layman makes
    requested action.
end note
layman [#FF0000]--> ltcsproxy: PATCH Current User\nResponse
deactivate layman
ltcsproxy [#0000FF]--> ltcc: PATCH Current User\nResponse
deactivate ltcsproxy
deactivate ltcc

legend left
    |Arrow color| Description |
    |<#0000FF>| Communication visible to browser |
    |<#FF0000>| Communication hidden from browser |
endlegend

@enduml