FROM geographica/gdal2:2.4.0

RUN mkdir /code
WORKDIR /code

RUN apt-get clean && apt-get update && \
    apt-get -y -qq install unzip curl python3-pip && \
    pip3 install pipenv

# http://click.pocoo.org/python3/
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY Pipfile* /code/

RUN pipenv install --system
