version: '2.1'

volumes:
   geoserver-data:

services:
   layman:
      container_name: layman
      build:
        context: .
        dockerfile: Dockerfile.production
      image: layman:latest
      command: bash start.sh
      env_file:
         - .env
      ports:
        - 8000:8000
      volumes:
        - ./geoserver_data:/geoserver_data
        - ./layman_data:/layman_data
        - ./src:/code/src
        - ./start.sh:/code/start.sh
      depends_on:
        hslayers:
          condition: service_started

   redis:
      image: redis:4.0.11-alpine

   celery_worker:
      image: layman:latest
      command: bash -c "cd src && python3 -m celery -Q $${LAYMAN_CELERY_QUEUE} -A layman.celery_app worker --loglevel=info"
      env_file: .env
      environment:
        - C_FORCE_ROOT=true
        - IS_CELERY_WORKER=true
      volumes:
        - ./layman_data:/layman_data
        - ./src:/code/src
      depends_on:
        - layman
        - redis

   flower:
      container_name: flower
      image: layman:latest
      command: bash -c "cd src && python3 -m flower -A layman.celery_app --port=5555"
      env_file: .env.dev
      volumes:
        - ./src:/code/src
      ports:
        - 5555:5555
      depends_on:
        - celery_worker

   hslayers:
      container_name: hslayers
      build:
        context: hslayers
        dockerfile: Dockerfile.production
        args:
           - LAYMAN_GS_HOST=${LAYMAN_GS_HOST}
           - LAYMAN_GS_PORT=${LAYMAN_GS_PORT}
      image: hslayers:latest
      command: sh -c "node proxy.js & ./node_modules/.bin/http-server dist/"
#      env_file:
#         - .env.dev
      ports:
        - 8080:8080
        - 8081:8081
