FROM layman:latest

WORKDIR /code

RUN apt-get install -y -qq chromium-browser

RUN (cd /tmp && curl -O https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip && unzip chromedriver_linux64.zip -d /usr/bin && rm chromedriver_linux64.zip)

RUN pipenv install --system --dev
