FROM geographica/gdal2:2.3.0

RUN mkdir /code
WORKDIR /code

RUN apt-get update && apt-get install -y -qq unzip curl python3-pip chromium-browser && pip3 install --upgrade pip

RUN (cd /tmp && curl -O https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip && unzip chromedriver_linux64.zip -d /usr/bin && rm chromedriver_linux64.zip)

# ttp://click.pocoo.org/python3/
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ADD requirements.* /code/
RUN pip install -r requirements.txt
RUN pip install -r requirements.test.txt
