FROM node:18-alpine

RUN mkdir /code
WORKDIR /code

RUN apk update && apk add nano

ADD package.json \
    /code/

RUN npm install

ADD index.html \
    index.js \
    server.js \
    /code/

ADD src /code/src

RUN npm run build
