FROM node:16-alpine

RUN mkdir /code
WORKDIR /code

RUN apk update && apk add nano

ADD package.json \
    package-lock.json \
    /code/

RUN npm ci

ADD index.html \
    index.js \
    server.js \
    /code/

ADD src /code/src

RUN npm run build
