FROM osgeo/gdal:ubuntu-small-3.3.0

# Configure apt for installing chromium and chromedriver from debian repos - START
# https://askubuntu.com/a/1206502

RUN apt-get clean && apt-get update && \
    apt-get -y -qq install debian-archive-keyring

RUN echo 'deb [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://security.debian.org/debian-security stable-security main\n\
deb-src [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://security.debian.org/debian-security stable-security main\n\
\n\
deb [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://security.debian.org/debian-security stable-security/updates main\n\
deb-src [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://security.debian.org/debian-security stable-security/updates main\n\
\n\
deb [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://deb.debian.org/debian stable main\n\
deb-src [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://deb.debian.org/debian stable main\n'\
>> /etc/apt/sources.list.d/debian-stable.list

RUN echo 'Explanation: Allow installing chromium from the debian repo.\n\
Package: chromium*\n\
Pin: origin "*.debian.org"\n\
Pin-Priority: 100\n\
\n\
Explanation: Avoid other packages from the debian repo.\n\
Package: *\n\
Pin: origin "*.debian.org"\n\
Pin-Priority: 1\n'\
>> /etc/apt/preferences.d/debian-chromium

# Configure apt for installing chromium and chromedriver from debian repos - END

RUN apt-get clean && apt-get update && apt-get upgrade -y && \
    apt-get -y -qq install nano python3-pip python3-lxml && \
    apt-get -y -qq install libwebpmux3=0.6.1-2.1 && \
    apt-get -y -qq install chromium chromium-driver && \
    pip install pipenv==2020.11.15

RUN mkdir /code
RUN chmod 777 /code
WORKDIR /code

# http://click.pocoo.org/python3/
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY Pipfile* /code/

RUN pipenv install --system --dev
