FROM geographica/gdal2:2.4.0

RUN apt-get clean && apt-get update && \
    apt-get -y -qq install unzip curl python3-pip chromium-browser && \
    pip3 install pipenv

RUN export MAIN_CHROME_VERSION=$(apt-cache policy chromium-browser | grep -oP "Installed: \K\w+") && \
    echo "Installed chromium-browser ${MAIN_CHROME_VERSION}" && \
    export CHROMEDRIVER_VERSION=$(curl https://chromedriver.storage.googleapis.com/ | grep -oP "(?<=<Key>)${MAIN_CHROME_VERSION}\.[0-9.]+(?=/chromedriver_linux64.zip</Key>)" | tail -1) && \
    echo "Installing chromedriver version ${CHROMEDRIVER_VERSION}" && \
    (cd /tmp && curl -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" && unzip chromedriver_linux64.zip -d /usr/bin && rm chromedriver_linux64.zip)

RUN mkdir /code
RUN chmod 777 /code
WORKDIR /code

# http://click.pocoo.org/python3/
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY Pipfile* /code/

RUN pipenv install --system --dev
