FROM osgeo/gdal:ubuntu-small-3.3.0

RUN sed -i -e 's|http://|https://|g' /etc/apt/sources.list && \
    apt-get clean && apt-get update && apt-get upgrade -y && \
    apt-get -y -qq install nano python3-pip python3-lxml && \
    apt-get -y -qq install firefox firefox-geckodriver && \
    pip install pipenv==2024.4.0

RUN mkdir /code
RUN chmod 777 /code
WORKDIR /code

# http://click.pocoo.org/python3/
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY Pipfile* /code/

RUN pipenv install --system --dev
