FROM node:18-alpine

RUN mkdir /code
WORKDIR /code

RUN apk update && apk add wget

ARG LAYMAN_CLIENT_VERSION
# https://stackoverflow.com/a/42144033
RUN test -n "LAYMAN_CLIENT_VERSION"

RUN wget "https://github.com/LayerManager/layman-test-client/archive/$LAYMAN_CLIENT_VERSION.tar.gz" -O client.tar.gz && \
    tar -xvf client.tar.gz --strip 1 && \
    rm client.tar.gz

RUN npm ci

ARG LTC_BASEPATH
RUN test -n "LTC_BASEPATH"
ENV LTC_BASEPATH=$LTC_BASEPATH

RUN npm run build
