name: IrritatingIntegrationTests

on:
  push:
    branches:
      - master
      - '[1-9].*.x'
  pull_request:
  workflow_dispatch:

jobs:
  IntegrationTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: View versions
        run: |
          docker -v
          docker-compose -v

      - name: Build
        run: |
          cp .env.test .env
          docker-compose -f docker-compose.deps.yml -f docker-compose.dev.yml build layman_dev
          docker-compose -f docker-compose.deps.yml -f docker-compose.test.yml pull redis postgresql nginx-qgis
          docker-compose -f docker-compose.deps.yml -f docker-compose.test.yml build --parallel qgis geoserver micka timgen layman_client_test

      - name: Download test data
        run: |
          mkdir -p tmp/artifacts
          docker-compose -f docker-compose.deps.yml -f docker-compose.test.yml run --rm --no-deps layman_test bash -c "bash ensure-test-data.sh"

      - name: Run tests
        run: |
          docker-compose -f docker-compose.deps.yml -f docker-compose.test.yml run --rm --no-deps -u root layman_test bash -c "cd src && python3 -B setup_geoserver.py"
          docker-compose -f docker-compose.deps.yml -f docker-compose.test.yml up --force-recreate --no-deps -d celery_worker_test
          docker-compose -f docker-compose.deps.yml -f docker-compose.test.yml run --rm --name layman_test_run_1 layman_test bash -c "python3 src/assert_db.py && python3 src/wait_for_deps.py && python3 src/clear_layman_data.py && python3 -m pytest -m irritating -W ignore::DeprecationWarning -xvv"


      - name: Save logs to files
        if: failure()
        run: |
          mkdir logs
          docker logs layman_celery_worker_test_1 &> logs/log_celery_worker.txt
          docker logs timgen &> logs/log_timgen.txt
          docker logs micka &> logs/log_micka.txt
          docker logs layman_geoserver_1 &> logs/log_geoserver.txt

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test_logs
          path: logs

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test_artifacts
          path: |
            tmp/artifacts/
            layman_data_test/
